### ISSUE TITLE
Add Support for Plugin Management

### ISSUE THREAD

**Issue by joshuacherry** [joshuacherry/ansible-role-grafana#1]
Something similar to the below should be added along with the ability to remove a plugin.

**task**
```
- name: Install plugins
  command: 'grafana-cli plugins install {{ item }}'
  args:
    creates: '/var/lib/grafana/plugins/{{ item }}'
  notify:
    - restart grafana-server
    - restart apache2
  with_items:
    - alexanderzobnin-zabbix-app
    - grafana-clock-panel
```

**inspec test**
```
describe file('/tmp') do
 it { should exist }
end
```
